### ISSUE TITLE
Tracking 404 Not Found Error Pages > wrong event listener DOMContentLoaded

### ISSUE THREAD

**Issue by simonelandi** [pirsch-analytics/docs#18]
Hi,
I would like to highlight a problem we encountered while implementing the 404 tracking script on a Wordpress website - without plugin and via js code snippet.
The documentation suggests to use the `DOMContentLoaded` event to listen to:
```
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", () => pirschNotFound());
</script>
```
but the error we had was:
`Reference Error: pirschNotFound is not defined`

From the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event):

> The load event is fired when the whole page has loaded, including all dependent resources such as stylesheets, scripts, iframes, and images. This is in contrast to [DOMContentLoaded](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event), which is fired as soon as the page DOM has been loaded, without waiting for resources to finish loading.

After switching from `DOMContentLoaded` to `load` your script have been working properly.
As the `pirsch-extended.js` library gets loaded via `defer`attribute I kindly suggest you to update your documentation in order to let others avoid this problem :)

**Comment by Kugelschieber** [comment]
Thanks for pointing this out! I have updated the article to use the load event instead of DOMContentLoaded :)
